# Services
services:
  local-api:
    build:
      dockerfile: api/Dockerfile
    ports:
      - 8080:8080
    networks:
      - backend
    hostname: local-api


  local-app:
    build:
      dockerfile: app/Dockerfile
    ports:
      - 8501:8501
    networks:
      - backend
    hostname: local-app

# Networks
networks:
  backend:
    driver: bridge
